<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.youyu</groupId>
		<artifactId>youyu-gateway</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>youyu-gateway-sdk</artifactId>
	<packaging>jar</packaging>
	<name>youyu-gateway-sdk</name>
	<description>Gateway SDK - User Info Parser</description>
	
	<dependencies>
		<!-- Common -->
		<dependency>
			<groupId>com.youyu</groupId>
			<artifactId>youyu-common</artifactId>
		</dependency>
		
		<!-- Base -->
		<dependency>
			<groupId>com.youyu</groupId>
			<artifactId>youyu-framework</artifactId>
		</dependency>
		
		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>
</project>
