<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.youyu</groupId>
		<artifactId>youyu-basics</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>youyu-basics-impl</artifactId>
	<name>youyu-basics-impl</name>
	<description>Basics Service Implementation Module - DDD四层架构实现</description>

	<dependencies>
		<dependency>
			<groupId>com.youyu</groupId>
			<artifactId>youyu-basics-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.youyu</groupId>
			<artifactId>youyu-starter</artifactId>
		</dependency>
	</dependencies>

</project>
